from pathlib import Path

RC = 'd91fe21d319d4f85832d9fc95d5912bbae23cf0e'
PREFLIGHT = '20260907-stage28e-h-prefix-fix-preflight-rc4'

handoff = Path('docs/STAGE28E_PHASE_H_HANDOFF.md')
h = handoff.read_text()
h = h.replace('## Latest H attempt: v5\n', '## Prior H attempt: v5\n', 1)
needle = '- Pre-closed-tent-preparation branch HEAD: `9042559b2d052b2e1942c0a61220bd9b7e74c97f`\n'
assert needle in h
h = h.replace(needle, needle + f'- Corrected closed-tent observer RC4 commit: `{RC}`\n- RC4 software-only preflight: `.agent/results/{PREFLIGHT}.json` — PASS\n', 1)
old = '''The RC observer is corrected to recognize the `stage28d_output ` marker anywhere in the serial line while preserving the same KV parsing and acceptance criteria. The preflight must regression-test both raw and ESP-IDF-prefixed forms before the next hardware H run.\n'''
new = f'''The RC observer is corrected to recognize the `stage28d_output ` marker anywhere in the serial line while preserving the same KV parsing and acceptance criteria. RC4 at `{RC}` passed synthetic raw/prefixed regression and replay acceptance of all `576/576` retained v6 output-state lines. The full software-only preflight `{PREFLIGHT}` also passed.\n'''
assert old in h
h = h.replace(old, new, 1)
old = '''## Software-only preflight required before overnight hardware\n\nBefore queueing the next real-output task, Local Agent must verify the exact current work-branch HEAD with `resources: []` and `allow_write=false`.\n\nRequired checks:\n\n1. fresh remote HEAD equals the expected RC SHA;\n2. local tree clean;\n3. `git show --check` / `git diff --check` clean;\n4. diff from pre-preparation HEAD `9042559b2d052b2e1942c0a61220bd9b7e74c97f` contains only intended `scripts/`/`docs/` files;\n5. no `.c/.cc/.cpp/.h/.hpp` production source changed;\n6. `python3 -m py_compile scripts/stage28e_phase_h_closed_tent.py`;\n7. `python3 scripts/stage28e_phase_h_closed_tent.py --help`;\n8. established focused/native host tests pass;\n9. established ESP-IDF firmware build passes without flashing;\n10. final local tree clean.\n\nDo not call the RC ready for the overnight run before this task has a terminal PASS result.\n'''
new = f'''## Software-only RC4 preflight — PASS\n\nTask:\n\n`.agent/results/{PREFLIGHT}.json`\n\nExecutable qualification-tooling RC commit:\n\n`{RC}`\n\nTerminal result: **PASS**. Verified:\n\n1. exact RC SHA and clean tree;\n2. diff from qualified firmware identity is restricted to the three handoff/status/continuation docs plus `scripts/stage28e_phase_h_closed_tent.py`;\n3. no production `.c/.cc/.cpp/.h/.hpp` source changed;\n4. Python compile/help;\n5. raw and ESP-IDF-prefixed parser regression;\n6. replay acceptance of all `576/576` v6 `stage28d_output` lines;\n7. complete host test suite;\n8. RF-disabled/fake ESP-IDF build with `CONFIG_ESP_MAIN_TASK_STACK_SIZE=12288`;\n9. RF-enabled/real ESP-IDF build with `CONFIG_ESP_MAIN_TASK_STACK_SIZE=16384`;\n10. final clean tree.\n\nAny later branch delta before the next hardware H task must be proven docs-only or the preflight must be rerun.\n'''
assert old in h
h = h.replace(old, new, 1)
old = 'A reasonable observer window is `--timeout 7200 --post-seconds 600`. A longer overnight observation may be used only if it remains bounded and the temperature/safety stop conditions stay active.\n'
new = 'For the immediate corrected H v7 qualification, use a bounded observer window that fits the Local Agent command budget together with mandatory recovery/final handling; the proven v6 environment produced repeated natural OFF/ON cycles within minutes once output lines are parsed correctly. A later overnight soak is a separate bounded test and must retain the same temperature/safety stop conditions.\n'
assert old in h
h = h.replace(old, new, 1)
handoff.write_text(h)

status = Path('docs/CURRENT_STATUS.md')
c = status.read_text()
needle = 'The observer now accepts `stage28d_output ` as an in-line marker so both raw and prefixed ESP-IDF serial forms are parsed. Production C/C++ remains unchanged. Formal H is still open until a corrected observer run proves the complete natural OFF->ON path and mandatory recovery/final.\n'
assert needle in c
c = c.replace(needle, needle + f'\nCorrected observer RC4: `{RC}`. Software-only preflight `{PREFLIGHT}` is PASS, including replay acceptance of all 576 retained v6 output-state lines, host suite, fake 12 KiB build, RF/real 16 KiB build and clean tree.\n', 1)
old = '''## Immediate next work\n\n1. Complete the software-only RC preflight for the closed-tent observer and current docs/scripts HEAD.\n2. Require clean tree, Python compile/help, focused host tests and an ESP-IDF build without flashing.\n3. Prove the delta from the previously qualified baseline contains only `scripts/`/`docs/` preparation files and no production C/C++ runtime change.\n4. Only after the preflight is green, prepare one immutable bounded overnight H task.\n5. The overnight task starts with the tent already closed, never waits for operator action, uses only the normal controller path, and always runs recovery/final fake-locked even if primary observation fails.\n6. Only after formal H PASS should the production modularity backlog begin.\n'''
new = f'''## Immediate next work\n\n1. Fresh-check branch/control state and confirm the corrected observer RC `{RC}` is still the executable qualification-tooling baseline; any later delta must be docs-only.\n2. Run one new immutable **H v7 corrected-parser** bounded hardware task on `board:growbox-s3` and `/dev/cu.usbserial-1130`.\n3. Start with the tent already closed; require no operator action, no request injection and no actuator forcing.\n4. Prove stable safety-clear physical fan OFF -> natural `requested_fan>=0.10` -> normal arbiter OFF->ON -> RF TX increment with zero errors -> unconfounded Shelly physical support.\n5. Regardless of primary outcome, always execute recovery RF and final RF-disabled `fake-locked`.\n6. If H v7 passes, formally close Stage28E H before starting the requested longer overnight soak / subsequent roadmap work.\n7. Keep the production runtime/service-console modularity refactor deferred until H is formally closed.\n'''
assert old in c
c = c.replace(old, new, 1)
status.write_text(c)

plan = Path('docs/CONTINUATION_PLAN.md')
p = plan.read_text()
start = p.index('## Latest H evidence\n')
end = p.index('## Repository-tracked closed-tent observer\n')
latest = f'''## Latest H evidence\n\nLatest attempt: H v6\n\n- task: `.agent/tasks/20260907-stage28e-h-v6-closed-autonomous.json`;\n- result: `.agent/results/20260907-stage28e-h-v6-closed-autonomous.json`;\n- formal primary outcome: FAIL;\n- recovery/final: PASS, final RF-disabled `fake-locked`;\n- production runtime remained healthy and reached `arbiter_transitions=46`, `tx=50`, `tx_errors=0`;\n- retained log contained `24` clean safety-clear OFF windows up to about `145 s`.\n\nRoot cause of the formal FAIL was qualification tooling: all `576/576` production `stage28d_output` lines were ESP-IDF-prefixed and the v6 observer incorrectly required a raw-line `startswith` match. Corrected observer RC4 commit: `{RC}`. Parser regression replay accepts all `576/576` retained lines. Full software-only preflight `{PREFLIGHT}` is PASS. Production C/C++ is unchanged relative to qualified firmware identity `5a4830db9d10e8cb73d4c617b09122f0844ad899`.\n\nH remains formally open only because the corrected observer has not yet been used for a successful physical H proof.\n\n'''
p = p[:start] + latest + p[end:]
old = '''## Before the overnight H run\n\nDo **not** start hardware qualification until the software-only release-candidate preflight is green.\n\nPreflight must verify the exact current branch HEAD and:\n\n1. clean working tree;\n2. changed-file set relative to the pre-preparation HEAD `9042559b2d052b2e1942c0a61220bd9b7e74c97f` is restricted to intended `scripts/`/`docs/` files;\n3. no production `.c/.cc/.cpp/.h/.hpp` source changed;\n4. `python3 -m py_compile scripts/stage28e_phase_h_closed_tent.py`;\n5. `python3 scripts/stage28e_phase_h_closed_tent.py --help`;\n6. focused/native host tests appropriate to the current controller/arbiter/safety/runtime code;\n7. ESP-IDF software build without flash using the repository's established build procedure;\n8. final clean working tree.\n\nIf the preflight fails, fix the RC first and use a new immutable Local Agent task id for the retry.\n'''
new = f'''## Software-only gate before corrected H v7\n\nRC4 preflight `{PREFLIGHT}` is **PASS** on `{RC}`. It proved clean scope/no production C++ delta, parser replay regression, full host suite, fake 12 KiB firmware build, RF/real 16 KiB firmware build and clean tree.\n\nBefore H v7, fresh-check branch HEAD and prove that any delta after `{RC}` is docs-only. If executable code/tooling changed, rerun the software gate with a new immutable task id.\n'''
assert old in p
p = p.replace(old, new, 1)
old_instr_start = p.index('## Recommended fresh-chat instruction\n')
# Replace the recommendation and discard the now-redundant trailing v6-finding section.
new_tail = f'''## Recommended fresh-chat instruction\n\n`Continue Growbox Stage28E Phase H only in MichalMatu/growbox-ml-controller. First read AGENTS.md, docs/STAGE28E_PHASE_H_HANDOFF.md, docs/CURRENT_STATUS.md, docs/CONTINUATION_PLAN.md, docs/GUIDANCE.md and docs/ESP32_S3_SERIAL_PORT_RESET.md, then fresh-check mvp/environment-controller HEAD and agent-control:.agent/status/daemon.json. A-G are formally complete; H is not. Qualified production firmware/source identity remains 5a4830db9d10e8cb73d4c617b09122f0844ad899. H v6 primary was a tooling false negative: all 576 stage28d_output lines were ESP-IDF-prefixed while the observer required startswith; the real run nevertheless had 24 clean OFF windows, 46 arbiter transitions, 50 RF TX and zero TX errors, and recovery/final fake-locked passed. Corrected observer RC4 is {RC}; software-only preflight {PREFLIGHT} is PASS, including 576/576 replay parser acceptance, host suite, fake 12 KiB build and RF/real 16 KiB build. The tent remains closed and no user action is needed. Next run one new immutable H v7 bounded hardware task on board:growbox-s3 and /dev/cu.usbserial-1130 using scripts/stage28e_phase_h_closed_tent.py, normal controller path only, no request injection/actuator forcing, and unconditional recovery plus final RF-disabled fake-locked. Never touch /dev/cu.usbserial-10. Do not start the production runtime/service-console modularity refactor until H formally passes.`\n'''
p = p[:old_instr_start] + new_tail
plan.write_text(p)
