// Generated by tools/schema/generate_environment_schema.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace growbox {
namespace control {
namespace schema {

inline constexpr std::uint32_t kSchemaVersion = 1U;
inline constexpr char kSchemaId[] = "environment-controller-v1";
inline constexpr char kSchemaHash[] = "e12b0cc20edf";
inline constexpr std::size_t kFeatureCount = 43U;
inline constexpr std::size_t kOutputCount = 4U;
inline constexpr std::uint8_t kHeaterControlTypeBinary = 0U;
inline constexpr std::uint8_t kHeaterControlTypePwm = 1U;

inline constexpr char kWireRootSensors[] = "sensors";
inline constexpr char kWireRootValidity[] = "validity";
inline constexpr char kWireRootEnvironment[] = "environment";
inline constexpr char kWireRootCultivation[] = "cultivation";
inline constexpr char kWireRootActuators[] = "actuators";
inline constexpr char kWireRootTargets[] = "targets";
inline constexpr char kWireRootPrevious[] = "previous";
inline constexpr char kWireObjectHeater[] = "heater";
inline constexpr char kWireObjectFan[] = "fan";
inline constexpr char kWireObjectHumidifier[] = "humidifier";
inline constexpr char kWireObjectIrrigation[] = "irrigation";

enum class FeatureIndex : std::size_t {
    AirTemperatureC = 0,
    AirHumidityPct = 1,
    Co2Ppm = 2,
    SoilMoisturePct = 3,
    OutsideTemperatureC = 4,
    OutsideHumidityPct = 5,
    AirTemperatureValid = 6,
    AirHumidityValid = 7,
    Co2Valid = 8,
    SoilMoistureValid = 9,
    OutsideTemperatureValid = 10,
    OutsideHumidityValid = 11,
    GrowboxVolumeM3 = 12,
    ThermalMassJPerK = 13,
    HeatLossWPerK = 14,
    AirLeakRateAch = 15,
    PotVolumeL = 16,
    SubstrateWaterCapacityMl = 17,
    TranspirationFactor = 18,
    HeaterAvailable = 19,
    HeaterMaxPowerW = 20,
    HeaterEfficiency = 21,
    HeaterControlType = 22,
    FanAvailable = 23,
    FanMaxAirflowM3H = 24,
    FanMinimumCommand = 25,
    FanControlType = 26,
    HumidifierAvailable = 27,
    HumidifierMaxOutputGH = 28,
    HumidifierControlType = 29,
    IrrigationAvailable = 30,
    IrrigationFlowMlS = 31,
    IrrigationMaximumPulseS = 32,
    IrrigationMinimumIntervalS = 33,
    IrrigationControlType = 34,
    TargetAirTemperatureC = 35,
    TargetAirHumidityPct = 36,
    TargetCo2Ppm = 37,
    TargetSoilMoisturePct = 38,
    PreviousHeater = 39,
    PreviousFan = 40,
    PreviousHumidifier = 41,
    PreviousIrrigation = 42,
};

enum class OutputIndex : std::size_t {
    Heater = 0,
    Fan = 1,
    Humidifier = 2,
    Irrigation = 3,
};

inline constexpr std::array<const char*, kFeatureCount> kFeatureNames{{
        "air_temperature_c",
        "air_humidity_pct",
        "co2_ppm",
        "soil_moisture_pct",
        "outside_temperature_c",
        "outside_humidity_pct",
        "air_temperature_valid",
        "air_humidity_valid",
        "co2_valid",
        "soil_moisture_valid",
        "outside_temperature_valid",
        "outside_humidity_valid",
        "growbox_volume_m3",
        "thermal_mass_j_per_k",
        "heat_loss_w_per_k",
        "air_leak_rate_ach",
        "pot_volume_l",
        "substrate_water_capacity_ml",
        "transpiration_factor",
        "heater_available",
        "heater_max_power_w",
        "heater_efficiency",
        "heater_control_type",
        "fan_available",
        "fan_max_airflow_m3_h",
        "fan_minimum_command",
        "fan_control_type",
        "humidifier_available",
        "humidifier_max_output_g_h",
        "humidifier_control_type",
        "irrigation_available",
        "irrigation_flow_ml_s",
        "irrigation_maximum_pulse_s",
        "irrigation_minimum_interval_s",
        "irrigation_control_type",
        "target_air_temperature_c",
        "target_air_humidity_pct",
        "target_co2_ppm",
        "target_soil_moisture_pct",
        "previous_heater",
        "previous_fan",
        "previous_humidifier",
        "previous_irrigation",
}};

inline constexpr std::array<const char*, kFeatureCount> kFeaturePaths{{
        "sensors.air_temperature_c",
        "sensors.air_humidity_pct",
        "sensors.co2_ppm",
        "sensors.soil_moisture_pct",
        "sensors.outside_temperature_c",
        "sensors.outside_humidity_pct",
        "validity.air_temperature_c",
        "validity.air_humidity_pct",
        "validity.co2_ppm",
        "validity.soil_moisture_pct",
        "validity.outside_temperature_c",
        "validity.outside_humidity_pct",
        "environment.growbox_volume_m3",
        "environment.thermal_mass_j_per_k",
        "environment.heat_loss_w_per_k",
        "environment.air_leak_rate_ach",
        "cultivation.pot_volume_l",
        "cultivation.substrate_water_capacity_ml",
        "cultivation.transpiration_factor",
        "actuators.heater.available",
        "actuators.heater.max_power_w",
        "actuators.heater.efficiency",
        "actuators.heater.control_type",
        "actuators.fan.available",
        "actuators.fan.max_airflow_m3_h",
        "actuators.fan.minimum_command",
        "actuators.fan.control_type",
        "actuators.humidifier.available",
        "actuators.humidifier.max_output_g_h",
        "actuators.humidifier.control_type",
        "actuators.irrigation.available",
        "actuators.irrigation.flow_ml_s",
        "actuators.irrigation.maximum_pulse_s",
        "actuators.irrigation.minimum_interval_s",
        "actuators.irrigation.control_type",
        "targets.air_temperature_c",
        "targets.air_humidity_pct",
        "targets.co2_ppm",
        "targets.soil_moisture_pct",
        "previous.heater",
        "previous.fan",
        "previous.humidifier",
        "previous.irrigation",
}};

inline constexpr std::array<const char*, kFeatureCount> kFeatureWireKeys{{
        "air_temperature_c",
        "air_humidity_pct",
        "co2_ppm",
        "soil_moisture_pct",
        "outside_temperature_c",
        "outside_humidity_pct",
        "air_temperature_c",
        "air_humidity_pct",
        "co2_ppm",
        "soil_moisture_pct",
        "outside_temperature_c",
        "outside_humidity_pct",
        "growbox_volume_m3",
        "thermal_mass_j_per_k",
        "heat_loss_w_per_k",
        "air_leak_rate_ach",
        "pot_volume_l",
        "substrate_water_capacity_ml",
        "transpiration_factor",
        "available",
        "max_power_w",
        "efficiency",
        "control_type",
        "available",
        "max_airflow_m3_h",
        "minimum_command",
        "control_type",
        "available",
        "max_output_g_h",
        "control_type",
        "available",
        "flow_ml_s",
        "maximum_pulse_s",
        "minimum_interval_s",
        "control_type",
        "air_temperature_c",
        "air_humidity_pct",
        "co2_ppm",
        "soil_moisture_pct",
        "heater",
        "fan",
        "humidifier",
        "irrigation",
}};

inline constexpr std::array<const char*, kFeatureCount> kFeatureUnits{{
        "degC",
        "percent",
        "ppm",
        "percent",
        "degC",
        "percent",
        "mask",
        "mask",
        "mask",
        "mask",
        "mask",
        "mask",
        "m3",
        "J/K",
        "W/K",
        "1/h",
        "L",
        "mL",
        "ratio",
        "mask",
        "W",
        "ratio",
        "enum",
        "mask",
        "m3/h",
        "ratio",
        "enum",
        "mask",
        "g/h",
        "enum",
        "mask",
        "mL/s",
        "s",
        "s",
        "enum",
        "degC",
        "percent",
        "ppm",
        "percent",
        "ratio",
        "ratio",
        "ratio",
        "ratio",
}};

inline constexpr std::array<float, kFeatureCount> kFeatureMinimums{{
        -20.0f,
        0.0f,
        0.0f,
        0.0f,
        -40.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.05f,
        1000.0f,
        0.0f,
        0.0f,
        0.1f,
        10.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        -20.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
}};

inline constexpr std::array<float, kFeatureCount> kFeatureMaximums{{
        60.0f,
        100.0f,
        5000.0f,
        100.0f,
        60.0f,
        100.0f,
        1.0f,
        1.0f,
        1.0f,
        1.0f,
        1.0f,
        1.0f,
        100.0f,
        10000000.0f,
        5000.0f,
        20.0f,
        100.0f,
        100000.0f,
        10.0f,
        1.0f,
        10000.0f,
        1.0f,
        1.0f,
        1.0f,
        10000.0f,
        1.0f,
        1.0f,
        1.0f,
        10000.0f,
        1.0f,
        1.0f,
        1000.0f,
        600.0f,
        86400.0f,
        1.0f,
        60.0f,
        100.0f,
        5000.0f,
        100.0f,
        1.0f,
        1.0f,
        1.0f,
        1.0f,
}};

inline constexpr std::array<float, kFeatureCount> kFeatureDefaults{{
        24.0f,
        60.0f,
        850.0f,
        50.0f,
        20.0f,
        50.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        1.0f,
        100000.0f,
        30.0f,
        1.0f,
        10.0f,
        3000.0f,
        1.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        1.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        25.0f,
        65.0f,
        850.0f,
        50.0f,
        0.0f,
        0.0f,
        0.0f,
        0.0f,
}};

inline constexpr std::array<const char*, kOutputCount> kOutputNames{{
        "heater",
        "fan",
        "humidifier",
        "irrigation",
}};

inline constexpr std::array<float, kOutputCount> kOutputMinimums{{
        0.0f,
        0.0f,
        0.0f,
        0.0f,
}};

inline constexpr std::array<float, kOutputCount> kOutputMaximums{{
        1.0f,
        1.0f,
        1.0f,
        1.0f,
}};

inline constexpr std::array<float, kOutputCount> kOutputDefaults{{
        0.0f,
        0.0f,
        0.0f,
        0.0f,
}};

inline constexpr float kDefaultMaximumAirTemperatureC = 35.0f;
inline constexpr float kDefaultAlarmAirTemperatureC = 32.0f;
inline constexpr float kDefaultAlarmMinimumFan = 0.6f;
inline constexpr float kDefaultBinaryThreshold = 0.5f;
inline constexpr float kDefaultHeaterMinimumOnS = 30.0f;
inline constexpr float kDefaultHeaterMinimumOffS = 30.0f;
inline constexpr float kDefaultHumidifierMinimumOnS = 15.0f;
inline constexpr float kDefaultHumidifierMinimumOffS = 15.0f;

constexpr std::size_t index(FeatureIndex value) noexcept {
    return static_cast<std::size_t>(value);
}

constexpr std::size_t index(OutputIndex value) noexcept {
    return static_cast<std::size_t>(value);
}

constexpr const char* wireKey(FeatureIndex value) noexcept {
    return kFeatureWireKeys[index(value)];
}

}  // namespace schema
}  // namespace control
}  // namespace growbox
