#pragma once

#include "EnvironmentTypes.h"

#include <cstddef>

namespace growbox {
namespace control {

// EnvironmentModel.h uses fixed global scratch buffers generated by emlearn.
// Consequently, calls to a ModelRuntime must be serialized by the application.
class ModelRuntime {
public:
  ModelRuntime() noexcept = default;

  ModelStatus infer(const FeatureVector& features, RawModelDecision& decision) const noexcept;

  static bool isSchemaCompatible(const char* model_schema_hash, std::size_t model_input_count,
                                 std::size_t model_output_count) noexcept;
  static bool isCompatible() noexcept;

  static const char* schemaHash() noexcept;
  static const char* modelSchemaHash() noexcept;
  static const char* modelVersion() noexcept;
  static std::size_t inputCount() noexcept;
  static std::size_t outputCount() noexcept;
};

} // namespace control
} // namespace growbox
