"""Export a trained Keras MLP to deterministic emlearn C++ headers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from .contract import PROJECT_ROOT, Contract, load_contract
from .generate_dataset import Dataset

DEFAULT_GENERATED_DIR = PROJECT_ROOT / "lib" / "environment_control" / "src" / "generated"
DEFAULT_GOLDEN_JSON = PROJECT_ROOT / "tests" / "fixtures" / "golden_vectors.json"
DEFAULT_GOLDEN_HEADER = PROJECT_ROOT / "tests" / "fixtures" / "ModelGoldenVectors.h"
EMLEARN_MODEL_NAME = "growbox_environment_model"


@dataclass(frozen=True)
class ExportResult:
    environment_model_header: Path
    model_manifest_header: Path
    golden_json: Path
    golden_header: Path
    model_version: str
    weight_hash: str


@contextmanager
def _working_directory(path: Path) -> Iterator[None]:
    previous = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


def _weight_hash(model: Any) -> str:
    digest = hashlib.sha256()
    for array in model.get_weights():
        contiguous = np.ascontiguousarray(array, dtype="<f4")
        digest.update(contiguous.tobytes(order="C"))
    return digest.hexdigest()


def _float_literal(value: float) -> str:
    numeric = float(value)
    if not np.isfinite(numeric):
        raise ValueError("generated C++ values must be finite")
    rendered = f"{numeric:.9g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "f"


def _quoted(values: tuple[str, ...]) -> str:
    return ",\n        ".join(json.dumps(value) for value in values)


def _floats(values: list[float] | tuple[float, ...]) -> str:
    return ",\n        ".join(_float_literal(value) for value in values)


def _emlearn_code(model: Any) -> str:
    import emlearn

    # emlearn's public conversion wrapper also compiles a host helper. Keep its
    # temporary objects away from the repository.
    with tempfile.TemporaryDirectory(prefix="growbox-emlearn-") as directory:
        with _working_directory(Path(directory)):
            converted = emlearn.convert(
                model,
                method="loadable",
                return_type="regressor",
            )
            code = converted.save(name=EMLEARN_MODEL_NAME)
    # eml_net.h is included before the generated body so its C declarations do
    # not accidentally become members of a C++ namespace.
    body = code.replace("#include <eml_net.h>", "").strip()
    return "\n".join(line.rstrip() for line in body.splitlines()) + "\n"


def render_environment_model_header(
    model: Any,
    contract: Contract,
    *,
    model_version: str,
    weight_hash: str,
) -> str:
    network = _emlearn_code(model)
    return f"""// Generated by python -m tools.ml.pipeline. Do not edit.
#pragma once

#include <cstddef>
#include <eml_net.h>

{network}
namespace generated_model {{

inline constexpr std::size_t kInputCount = {len(contract.features)}U;
inline constexpr std::size_t kOutputCount = {len(contract.outputs)}U;
inline constexpr char kSchemaHash[] = "{contract.short_hash}";
inline constexpr char kModelVersion[] = "{model_version}";
inline constexpr char kWeightHash[] = "{weight_hash[:12]}";

inline bool infer(const float* features, float* outputs) {{
    if (features == nullptr || outputs == nullptr) {{
        return false;
    }}
    return {EMLEARN_MODEL_NAME}_regress(
        features,
        static_cast<int32_t>(kInputCount),
        outputs,
        static_cast<int32_t>(kOutputCount)) == EmlOk;
}}

}}  // namespace generated_model
"""


def _metric(metrics: Mapping[str, object], section: str, key: str) -> float:
    selected = metrics.get(section)
    if not isinstance(selected, Mapping) or key not in selected:
        raise ValueError(f"missing metric {section}.{key}")
    return float(selected[key])


def render_manifest_header(
    contract: Contract,
    dataset: Dataset,
    metrics: Mapping[str, object],
    *,
    mode: str,
    training_seed: int,
    model_version: str,
    weight_hash: str,
) -> str:
    minimums = [feature.minimum for feature in contract.features]
    maximums = [feature.maximum for feature in contract.features]
    defaults = [feature.default for feature in contract.features]
    test = metrics.get("test")
    if not isinstance(test, Mapping):
        raise ValueError("metrics do not contain test results")
    per_output = test.get("per_output")
    if not isinstance(per_output, Mapping):
        raise ValueError("metrics do not contain per-output test results")
    output_mae = [round(float(per_output[name]["mae"]), 7) for name in contract.outputs]
    output_rmse = [round(float(per_output[name]["rmse"]), 7) for name in contract.outputs]
    parameter_count = int(metrics.get("parameter_count", 0))
    weight_decimals = int(metrics.get("export_weight_decimals", 0))
    return f"""// Generated by python -m tools.ml.pipeline. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace generated_manifest {{

inline constexpr std::uint32_t kSchemaVersion = {contract.schema_version}U;
inline constexpr char kSchemaHash[] = "{contract.short_hash}";
inline constexpr char kModelVersion[] = "{model_version}";
inline constexpr char kWeightHash[] = "{weight_hash}";
inline constexpr char kModelFormat[] = "emlearn-net-float32-loadable";
inline constexpr char kTrainingMode[] = "{mode}";
inline constexpr std::uint32_t kTrainingSeed = {training_seed}U;
inline constexpr std::size_t kDatasetSize = {len(dataset.features)}U;
inline constexpr std::size_t kParameterCount = {parameter_count}U;
inline constexpr std::uint32_t kExportWeightDecimalPlaces = {weight_decimals}U;
inline constexpr std::size_t kInputCount = {len(contract.features)}U;
inline constexpr std::size_t kOutputCount = {len(contract.outputs)}U;

inline constexpr std::array<const char*, kInputCount> kFeatureOrder{{{{
        {_quoted(contract.feature_names)}
}}}};

inline constexpr std::array<const char*, kOutputCount> kOutputOrder{{{{
        {_quoted(contract.outputs)}
}}}};

inline constexpr std::array<float, kInputCount> kNormalizationMinimums{{{{
        {_floats(minimums)}
}}}};

inline constexpr std::array<float, kInputCount> kNormalizationMaximums{{{{
        {_floats(maximums)}
}}}};

inline constexpr std::array<float, kInputCount> kNormalizationDefaults{{{{
        {_floats(defaults)}
}}}};

inline constexpr float kTestMae = {_float_literal(round(_metric(metrics, "test", "mae"), 7))};
inline constexpr float kTestRmse = {_float_literal(round(_metric(metrics, "test", "rmse"), 7))};
inline constexpr float kTestMaxAbsError = {_float_literal(round(_metric(metrics, "test", "max_abs_error"), 7))};
inline constexpr std::array<float, kOutputCount> kTestOutputMae{{{{
        {_floats(output_mae)}
}}}};
inline constexpr std::array<float, kOutputCount> kTestOutputRmse{{{{
        {_floats(output_rmse)}
}}}};

}}  // namespace generated_manifest
"""


def _golden_vectors(
    model: Any,
    dataset: Dataset,
    contract: Contract,
    *,
    model_version: str,
    count: int = 3,
) -> dict[str, object]:
    test_indices = np.flatnonzero(dataset.splits == "test")
    if len(test_indices) < count:
        raise ValueError("not enough test rows for golden vectors")
    # Prefer different scenarios so the fixture covers substantially different
    # normalized inputs.
    selected: list[int] = []
    seen: set[str] = set()
    for raw_index in test_indices:
        index = int(raw_index)
        scenario_id = str(dataset.scenario_ids[index])
        if scenario_id in seen:
            continue
        seen.add(scenario_id)
        selected.append(index)
        if len(selected) == count:
            break
    if len(selected) < count:
        for raw_index in test_indices:
            index = int(raw_index)
            if index not in selected:
                selected.append(index)
            if len(selected) == count:
                break
    features = dataset.features[selected].astype(np.float32)
    predictions = np.asarray(model(features, training=False), dtype=np.float32)
    vectors = []
    for feature_row, prediction_row in zip(features, predictions):
        vectors.append(
            {
                "features": [round(float(value), 9) for value in feature_row],
                "expected": [round(float(value), 7) for value in prediction_row],
            }
        )
    return {
        "schema_version": contract.schema_version,
        "schema_hash": contract.short_hash,
        "model_version": model_version,
        "feature_order": list(contract.feature_names),
        "output_order": list(contract.outputs),
        "vectors": vectors,
    }


def render_golden_header(golden: Mapping[str, object]) -> str:
    vectors = golden["vectors"]
    if not isinstance(vectors, list) or not vectors:
        raise ValueError("golden fixture has no vectors")
    input_count = len(vectors[0]["features"])
    output_count = len(vectors[0]["expected"])
    feature_rows = []
    output_rows = []
    for vector in vectors:
        feature_rows.append(
            "        {{" + ", ".join(_float_literal(value) for value in vector["features"]) + "}}"
        )
        output_rows.append(
            "        {{" + ", ".join(_float_literal(value) for value in vector["expected"]) + "}}"
        )
    rendered_features = ",\n".join(feature_rows)
    rendered_outputs = ",\n".join(output_rows)
    return f"""// Generated by python -m tools.ml.pipeline. Do not edit.
#pragma once

#include <array>
#include <cstddef>

namespace model_golden_vectors {{

inline constexpr std::size_t kVectorCount = {len(vectors)}U;
inline constexpr std::size_t kInputCount = {input_count}U;
inline constexpr std::size_t kOutputCount = {output_count}U;
inline constexpr char kSchemaHash[] = "{golden["schema_hash"]}";
inline constexpr char kModelVersion[] = "{golden["model_version"]}";

inline constexpr std::array<std::array<float, kInputCount>, kVectorCount> kFeatures{{{{
{rendered_features}
}}}};
inline constexpr std::array<std::array<float, kOutputCount>, kVectorCount> kExpected{{{{
{rendered_outputs}
}}}};

}}  // namespace model_golden_vectors
"""


def export_model(
    model: Any,
    dataset: Dataset,
    metrics: Mapping[str, object],
    *,
    contract: Contract | None = None,
    mode: str,
    training_seed: int,
    generated_dir: Path = DEFAULT_GENERATED_DIR,
    golden_json: Path = DEFAULT_GOLDEN_JSON,
    golden_header: Path = DEFAULT_GOLDEN_HEADER,
) -> ExportResult:
    contract = contract or load_contract()
    if tuple(dataset.feature_names) != contract.feature_names:
        raise ValueError("dataset feature order does not match the contract")
    if tuple(dataset.output_names) != contract.outputs:
        raise ValueError("dataset output order does not match the contract")
    weight_hash = _weight_hash(model)
    model_version = f"environment-mlp-v1-{mode}-{weight_hash[:12]}"
    environment_header = render_environment_model_header(
        model,
        contract,
        model_version=model_version,
        weight_hash=weight_hash,
    )
    manifest_header = render_manifest_header(
        contract,
        dataset,
        metrics,
        mode=mode,
        training_seed=training_seed,
        model_version=model_version,
        weight_hash=weight_hash,
    )
    golden = _golden_vectors(model, dataset, contract, model_version=model_version)

    model_path = generated_dir / "EnvironmentModel.h"
    manifest_path = generated_dir / "ModelManifest.h"
    for path in (model_path, manifest_path, golden_json, golden_header):
        path.parent.mkdir(parents=True, exist_ok=True)
    model_path.write_text(environment_header, encoding="utf-8")
    manifest_path.write_text(manifest_header, encoding="utf-8")
    golden_json.write_text(json.dumps(golden, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    golden_header.write_text(render_golden_header(golden), encoding="utf-8")
    return ExportResult(
        environment_model_header=model_path,
        model_manifest_header=manifest_path,
        golden_json=golden_json,
        golden_header=golden_header,
        model_version=model_version,
        weight_hash=weight_hash,
    )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--metrics", type=Path, required=True)
    parser.add_argument("--mode", choices=("quick", "full"), required=True)
    parser.add_argument("--seed", type=int, default=1847)
    parser.add_argument("--generated-dir", type=Path, default=DEFAULT_GENERATED_DIR)
    parser.add_argument("--golden-json", type=Path, default=DEFAULT_GOLDEN_JSON)
    parser.add_argument("--golden-header", type=Path, default=DEFAULT_GOLDEN_HEADER)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
    import tensorflow as tf

    model = tf.keras.models.load_model(args.model)
    dataset = Dataset.load(args.dataset)
    metrics = json.loads(args.metrics.read_text(encoding="utf-8"))
    result = export_model(
        model,
        dataset,
        metrics,
        mode=args.mode,
        training_seed=args.seed,
        generated_dir=args.generated_dir,
        golden_json=args.golden_json,
        golden_header=args.golden_header,
    )
    print(f"exported {result.model_version} to {result.environment_model_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
