#!/usr/bin/env python3
"""Generate the climate-only v6 C++ contract header."""
from __future__ import annotations
import argparse
import hashlib
import json
import math
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA = ROOT / "schemas" / "environment-controller.v6.json"
DEFAULT_OUTPUT = ROOT / "lib" / "environment_control" / "src" / "climate" / "ClimateContract.h"
EXPECTED_OUTPUTS = ("heater", "cooler", "exhaust_fan", "humidifier", "dehumidifier", "co2_doser")
BANNED_FEATURE_TOKENS = ("pot", "soil", "nutrient", "irrigation", "leaf", "ppfd")

def canonical_bytes(document: dict[str, Any]) -> bytes:
    return json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")

def schema_hash(document: dict[str, Any]) -> str:
    length = int(document["hash"]["short_hex_characters"])
    return hashlib.sha256(canonical_bytes(document)).hexdigest()[:length]

def cpp_identifier(name: str) -> str:
    pieces = re.findall(r"[A-Za-z0-9]+", name)
    value = "".join(piece[:1].upper() + piece[1:] for piece in pieces)
    if not value:
        raise ValueError(f"cannot form C++ identifier from {name!r}")
    return f"N{value}" if value[0].isdigit() else value

def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

def cpp_float(value: float) -> str:
    numeric = float(value)
    if not math.isfinite(numeric):
        raise ValueError("schema numeric literals must be finite")
    rendered = f"{numeric:.9g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "f"

def validate(document: dict[str, Any]) -> None:
    if document.get("schema_version") != 6 or document.get("contract_id") != "climate-mvp-v1":
        raise ValueError("unexpected climate v6 contract identity")
    model = document.get("model", {})
    features = model.get("features")
    outputs = model.get("outputs")
    if not isinstance(features, list) or not isinstance(outputs, list):
        raise ValueError("model features and outputs must be lists")
    if model.get("feature_count") != 38 or len(features) != 38:
        raise ValueError("climate v6 must contain exactly 38 features")
    if model.get("output_count") != 6 or len(outputs) != 6:
        raise ValueError("climate v6 must contain exactly 6 outputs")
    names = [str(item["name"]) for item in features]
    paths = [str(item["path"]) for item in features]
    if len(names) != len(set(names)) or len(paths) != len(set(paths)):
        raise ValueError("climate feature names and paths must be unique")
    output_names = tuple(str(item["name"]) for item in outputs)
    if output_names != EXPECTED_OUTPUTS:
        raise ValueError(f"unexpected output order: {output_names!r}")
    for name, path in zip(names, paths):
        haystack = f"{name} {path}".lower()
        if any(token in haystack for token in BANNED_FEATURE_TOKENS):
            raise ValueError(f"non-climate feature leaked into v6: {name}")
    for item in [*features, *outputs]:
        lo = float(item["minimum"])
        hi = float(item["maximum"])
        default = float(item["default"])
        if not all(math.isfinite(v) for v in (lo, hi, default)) or lo > hi or not lo <= default <= hi:
            raise ValueError(f"invalid range/default for {item['name']}")

def render(document: dict[str, Any]) -> str:
    validate(document)
    features = document["model"]["features"]
    outputs = document["model"]["outputs"]
    feature_enum = "\n".join(f"  {cpp_identifier(item['name'])} = {i}U," for i, item in enumerate(features))
    output_enum = "\n".join(f"  {cpp_identifier(item['name'])} = {i}U," for i, item in enumerate(outputs))
    def arr(items: list[str]) -> str:
        return "\n".join(f"    {item}," for item in items)
    return f"""// Generated by tools/schema/generate_climate_contract.py. Do not edit.
#pragma once
#include <array>
#include <cstddef>
#include <cstdint>
namespace growbox::climate::contract {{
inline constexpr std::uint32_t kSchemaVersion = 6U;
inline constexpr char kSchemaId[] = {cpp_string(document['schema_id'])};
inline constexpr char kContractId[] = {cpp_string(document['contract_id'])};
inline constexpr char kSchemaHash[] = {cpp_string(schema_hash(document))};
inline constexpr std::size_t kFeatureCount = {len(features)}U;
inline constexpr std::size_t kOutputCount = {len(outputs)}U;
inline constexpr std::uint64_t kTrendWindowMs = {int(float(document['model']['trend_window_target_s']) * 1000)}ULL;
enum class FeatureIndex : std::size_t {{
{feature_enum}
}};
enum class OutputIndex : std::size_t {{
{output_enum}
}};
inline constexpr std::array<const char*, kFeatureCount> kFeatureNames{{{{
{arr([cpp_string(x['name']) for x in features])}
}}}};
inline constexpr std::array<const char*, kFeatureCount> kFeaturePaths{{{{
{arr([cpp_string(x['path']) for x in features])}
}}}};
inline constexpr std::array<float, kFeatureCount> kFeatureMinimums{{{{
{arr([cpp_float(x['minimum']) for x in features])}
}}}};
inline constexpr std::array<float, kFeatureCount> kFeatureMaximums{{{{
{arr([cpp_float(x['maximum']) for x in features])}
}}}};
inline constexpr std::array<float, kFeatureCount> kFeatureDefaults{{{{
{arr([cpp_float(x['default']) for x in features])}
}}}};
inline constexpr std::array<const char*, kOutputCount> kOutputNames{{{{
{arr([cpp_string(x['name']) for x in outputs])}
}}}};
constexpr std::size_t index(FeatureIndex value) noexcept {{ return static_cast<std::size_t>(value); }}
constexpr std::size_t index(OutputIndex value) noexcept {{ return static_cast<std::size_t>(value); }}
}}  // namespace growbox::climate::contract
"""

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = json.loads(args.schema.read_text(encoding="utf-8"))
    generated = render(document)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated climate contract header is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(f"wrote {args.output} hash={schema_hash(document)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
