from pathlib import Path
p = Path('src/climate/runtime/Stage28ServiceConsoleCommand.cpp')
text = p.read_text()
old = '''  if (count==1U) {\n    if (equalsIgnoreCase(tokens[0],"help")||equalsIgnoreCase(tokens[0],"menu")||tokens[0]=="?"||tokens[0]=="0") { command.kind=ServiceConsoleCommandKind::Help; return command; }\n    if (equalsIgnoreCase(tokens[0],"status")||tokens[0]=="1") { command.kind=ServiceConsoleCommandKind::Status; return command; }\n    if (equalsIgnoreCase(tokens[0],"sensors")||tokens[0]=="2") { command.kind=ServiceConsoleCommandKind::Sensors; return command; }\n    if (equalsIgnoreCase(tokens[0],"rf")||tokens[0]=="3") { command.kind=ServiceConsoleCommandKind::RfList; return command; }\n    return invalidCommand();\n  }\n  if (equalsIgnoreCase(tokens[0],"automation")) {\n    if (count==1U || (count==2U && equalsIgnoreCase(tokens[1],"status"))) { command.kind=ServiceConsoleCommandKind::AutomationStatus; return command; }\n    if (count==2U && equalsIgnoreCase(tokens[1],"on")) { command.kind=ServiceConsoleCommandKind::AutomationEnable; return command; }\n    if (count==2U && equalsIgnoreCase(tokens[1],"off")) { command.kind=ServiceConsoleCommandKind::AutomationDisable; return command; }\n    return invalidCommand();\n  }\n'''
new = '''  if (equalsIgnoreCase(tokens[0],"automation")) {\n    if (count==1U || (count==2U && equalsIgnoreCase(tokens[1],"status"))) { command.kind=ServiceConsoleCommandKind::AutomationStatus; return command; }\n    if (count==2U && equalsIgnoreCase(tokens[1],"on")) { command.kind=ServiceConsoleCommandKind::AutomationEnable; return command; }\n    if (count==2U && equalsIgnoreCase(tokens[1],"off")) { command.kind=ServiceConsoleCommandKind::AutomationDisable; return command; }\n    return invalidCommand();\n  }\n  if (count==1U) {\n    if (equalsIgnoreCase(tokens[0],"help")||equalsIgnoreCase(tokens[0],"menu")||tokens[0]=="?"||tokens[0]=="0") { command.kind=ServiceConsoleCommandKind::Help; return command; }\n    if (equalsIgnoreCase(tokens[0],"status")||tokens[0]=="1") { command.kind=ServiceConsoleCommandKind::Status; return command; }\n    if (equalsIgnoreCase(tokens[0],"sensors")||tokens[0]=="2") { command.kind=ServiceConsoleCommandKind::Sensors; return command; }\n    if (equalsIgnoreCase(tokens[0],"rf")||tokens[0]=="3") { command.kind=ServiceConsoleCommandKind::RfList; return command; }\n    return invalidCommand();\n  }\n'''
if text.count(old) != 1:
    raise SystemExit(f'parser fix expected one match, found {text.count(old)}')
p.write_text(text.replace(old, new, 1))
print('A8_4_FIX_PASS')
