from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    assert count == 1, (path, count, old[:100])
    p.write_text(text.replace(old, new, 1))


replace_once(
    'lib/environment_control/src/climate/ClimateControlLoop.h',
    '''  virtual bool applyAndReport(const ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n                              ClimatePolicyRequest& confirmed_applied) noexcept {\n    const bool ok = apply(request, monotonic_ms);\n    confirmed_applied = ok ? request : ClimatePolicyRequest{};\n    return ok;\n  }\n\n  // Fail-safe OFF must bypass ordinary dwell/hysteresis in hardware adapters.\n''',
    '''  virtual bool applyAndReport(const ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n                              ClimatePolicyRequest& confirmed_applied) noexcept {\n    const bool ok = apply(request, monotonic_ms);\n    confirmed_applied = ok ? request : ClimatePolicyRequest{};\n    return ok;\n  }\n\n  // Execution-aware sink contract. Compatibility sinks report a complete accepted\n  // request; supervisor-backed sinks override this with command-truth projection.\n  virtual bool applyAndReportExecution(const ClimatePolicyRequest& request,\n                                       std::uint64_t monotonic_ms,\n                                       ClimateExecutionProjection& execution) noexcept {\n    execution = {};\n    ClimatePolicyRequest confirmed_applied{};\n    const bool ok = applyAndReport(request, monotonic_ms, confirmed_applied);\n    if (!ok) {\n      return false;\n    }\n    execution.executed = confirmed_applied;\n    execution.known_mask = ClimateExecutionKnownAll;\n    return true;\n  }\n\n  // Fail-safe OFF must bypass ordinary dwell/hysteresis in hardware adapters.\n''')

replace_once(
    'lib/environment_control/src/climate/ClimateControlLoop.cpp',
    '''  result.runtime_status = runtime_.step(input, monotonic_ms, decision);\n  ClimatePolicyRequest confirmed_applied{};\n  result.command_applied =\n      actuator_sink_.applyAndReport(decision.applied, monotonic_ms, confirmed_applied);\n  if (result.command_applied) {\n    ClimateExecutionProjection execution{};\n    execution.executed = confirmed_applied;\n    execution.known_mask = ClimateExecutionKnownAll;\n    runtime_.reconcileExecution(execution, input.capabilities, decision);\n    previous_applied_ = previousFromRequest(decision.applied);\n    result.io_status =\n        result.input_sampled ? ClimateLoopIoStatus::Ok : ClimateLoopIoStatus::InputUnavailable;\n    return result;\n  }\n''',
    '''  result.runtime_status = runtime_.step(input, monotonic_ms, decision);\n  ClimateExecutionProjection execution{};\n  result.command_applied =\n      actuator_sink_.applyAndReportExecution(decision.applied, monotonic_ms, execution);\n  if (result.command_applied) {\n    runtime_.reconcileExecution(execution, input.capabilities, decision);\n    // Keep the historical snapshot only as a compatibility mirror. The next\n    // cycle consumes execution feedback first, so production supervisor truth\n    // owns previous-state semantics.\n    previous_applied_ = previousFromRequest(decision.applied);\n    setPreviousExecutionFeedback(execution);\n    result.io_status =\n        result.input_sampled ? ClimateLoopIoStatus::Ok : ClimateLoopIoStatus::InputUnavailable;\n    return result;\n  }\n''')

replace_once(
    'src/climate/output/ClimateOutputSupervisorSink.h',
    '''  bool applyAndReport(const ::growbox::climate::ClimatePolicyRequest& request,\n                      std::uint64_t monotonic_ms,\n                      ::growbox::climate::ClimatePolicyRequest& executed_projection) noexcept override;\n  bool applyFailSafeOff(std::uint64_t monotonic_ms) noexcept override;\n''',
    '''  bool applyAndReport(const ::growbox::climate::ClimatePolicyRequest& request,\n                      std::uint64_t monotonic_ms,\n                      ::growbox::climate::ClimatePolicyRequest& executed_projection) noexcept override;\n  bool applyAndReportExecution(\n      const ::growbox::climate::ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n      ::growbox::climate::ClimateExecutionProjection& execution) noexcept override;\n  bool applyFailSafeOff(std::uint64_t monotonic_ms) noexcept override;\n''')

replace_once(
    'src/climate/output/ClimateOutputSupervisorSink.h',
    '''  bool projectExecutedClimate(\n      ::growbox::climate::ClimatePolicyRequest& projection) const noexcept;\n''',
    '''  bool projectExecutedClimate(\n      ::growbox::climate::ClimateExecutionProjection& projection) const noexcept;\n''')

replace_once(
    'src/climate/output/ClimateOutputSupervisorSink.cpp',
    '''float normalizedLevel(float value) noexcept {\n  return std::clamp(value, 0.0F, 1.0F);\n}\n\n} // namespace\n''',
    '''float normalizedLevel(float value) noexcept {\n  return std::clamp(value, 0.0F, 1.0F);\n}\n\n::growbox::climate::ClimateExecutionKnownMask executionKnownMask(\n    ClimateActuatorRole role) noexcept {\n  switch (role) {\n  case ClimateActuatorRole::Heater:\n    return ::growbox::climate::ClimateExecutionKnownHeater;\n  case ClimateActuatorRole::Cooler:\n    return ::growbox::climate::ClimateExecutionKnownCooler;\n  case ClimateActuatorRole::ExhaustFan:\n    return ::growbox::climate::ClimateExecutionKnownExhaustFan;\n  case ClimateActuatorRole::Humidifier:\n    return ::growbox::climate::ClimateExecutionKnownHumidifier;\n  case ClimateActuatorRole::Dehumidifier:\n    return ::growbox::climate::ClimateExecutionKnownDehumidifier;\n  case ClimateActuatorRole::Co2Doser:\n    return ::growbox::climate::ClimateExecutionKnownCo2Doser;\n  }\n  return ::growbox::climate::ClimateExecutionKnownNone;\n}\n\n} // namespace\n''')

old_projection = '''bool ClimateOutputSupervisorSink::projectExecutedClimate(\n    ::growbox::climate::ClimatePolicyRequest& projection) const noexcept {\n  projection = {};\n  if (config_status_ != ClimateSemanticOutputConfigStatus::Ok) {\n    return false;\n  }\n\n  ::growbox::app::output::ExecutedControlProjection executed{};\n  if (!::growbox::app::output::buildExecutedControlProjection(\n          last_resolution_, last_report_, state_store_, executed)) {\n    return false;\n  }\n\n  for (const auto role : kClimateRoles) {\n    const std::size_t role_index = climateRoleIndex(role);\n    if (role_index >= climate_config_.roles.size()) {\n      projection = {};\n      return false;\n    }\n    const auto& mapping = climate_config_.roles[role_index];\n    if (!mapping.enabled) {\n      continue;\n    }\n    const auto* endpoint = ::growbox::app::output::findExecutedEndpointProjection(\n        executed, mapping.endpoint);\n    if (endpoint == nullptr || !endpoint->has_executed_state) {\n      projection = {};\n      return false;\n    }\n    const float level = endpoint->executed_state ==\n                                ::growbox::app::output::BinaryOutputState::On\n                            ? 1.0F\n                            : 0.0F;\n    setRoleLevel(projection, role, level);\n  }\n  return true;\n}\n'''
new_projection = '''bool ClimateOutputSupervisorSink::projectExecutedClimate(\n    ::growbox::climate::ClimateExecutionProjection& projection) const noexcept {\n  projection = {};\n  if (config_status_ != ClimateSemanticOutputConfigStatus::Ok) {\n    return false;\n  }\n\n  ::growbox::app::output::ExecutedControlProjection executed{};\n  if (!::growbox::app::output::buildExecutedControlProjection(\n          last_resolution_, last_report_, state_store_, executed)) {\n    return false;\n  }\n\n  for (const auto role : kClimateRoles) {\n    const std::size_t role_index = climateRoleIndex(role);\n    if (role_index >= climate_config_.roles.size()) {\n      projection = {};\n      return false;\n    }\n    const auto mask = executionKnownMask(role);\n    if (mask == ::growbox::climate::ClimateExecutionKnownNone) {\n      projection = {};\n      return false;\n    }\n    const auto& mapping = climate_config_.roles[role_index];\n    if (!mapping.enabled) {\n      // Unsupported climate roles are rejected unless requested at zero, so zero\n      // is honest semantic execution truth for those roles.\n      setRoleLevel(projection.executed, role, 0.0F);\n      projection.known_mask |= static_cast<std::uint8_t>(mask);\n      continue;\n    }\n    const auto* endpoint = ::growbox::app::output::findExecutedEndpointProjection(\n        executed, mapping.endpoint);\n    if (endpoint == nullptr || !endpoint->has_executed_state) {\n      projection = {};\n      return false;\n    }\n    const float level = endpoint->executed_state ==\n                                ::growbox::app::output::BinaryOutputState::On\n                            ? 1.0F\n                            : 0.0F;\n    setRoleLevel(projection.executed, role, level);\n    projection.known_mask |= static_cast<std::uint8_t>(mask);\n  }\n  return projection.known_mask ==\n         static_cast<std::uint8_t>(::growbox::climate::ClimateExecutionKnownAll);\n}\n'''
replace_once('src/climate/output/ClimateOutputSupervisorSink.cpp', old_projection, new_projection)

old_apply_report = '''bool ClimateOutputSupervisorSink::applyAndReport(\n    const ::growbox::climate::ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n    ::growbox::climate::ClimatePolicyRequest& executed_projection) noexcept {\n  executed_projection = {};\n  ::growbox::app::output::ControlIntent control{};\n  if (!buildControlIntent(request, monotonic_ms, control)) {\n    return false;\n  }\n\n  bool transport_completed = false;\n  if (!executeCycle(control, monotonic_ms, transport_completed)) {\n    return false;\n  }\n  if (!projectExecutedClimate(executed_projection)) {\n    executed_projection = {};\n    return false;\n  }\n  return transport_completed;\n}\n'''
new_apply_report = '''bool ClimateOutputSupervisorSink::applyAndReportExecution(\n    const ::growbox::climate::ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n    ::growbox::climate::ClimateExecutionProjection& execution) noexcept {\n  execution = {};\n  ::growbox::app::output::ControlIntent control{};\n  if (!buildControlIntent(request, monotonic_ms, control)) {\n    return false;\n  }\n\n  bool transport_completed = false;\n  if (!executeCycle(control, monotonic_ms, transport_completed)) {\n    return false;\n  }\n  if (!projectExecutedClimate(execution)) {\n    execution = {};\n    return false;\n  }\n  return transport_completed;\n}\n\nbool ClimateOutputSupervisorSink::applyAndReport(\n    const ::growbox::climate::ClimatePolicyRequest& request, std::uint64_t monotonic_ms,\n    ::growbox::climate::ClimatePolicyRequest& executed_projection) noexcept {\n  ::growbox::climate::ClimateExecutionProjection execution{};\n  const bool completed = applyAndReportExecution(request, monotonic_ms, execution);\n  executed_projection = execution.executed;\n  return completed;\n}\n'''
replace_once('src/climate/output/ClimateOutputSupervisorSink.cpp', old_apply_report, new_apply_report)

replace_once(
    'test/test_climate_control_loop/test_main.cpp',
    '''  assert(near(loop.previousApplied().exhaust_fan, 1.0F));\n  assert(decision.effective_after.exhaust_fan > 0.6F);\n}\n''',
    '''  assert(near(loop.previousApplied().exhaust_fan, 1.0F));\n  assert(loop.hasExternalPreviousExecutionFeedback());\n  assert(decision.effective_after.exhaust_fan > 0.6F);\n}\n''')

insert_before = '''void testPartialFailureReturnsFalseAndProjectsLastSuccessfulCommands() {\n'''
new_test = '''void testExecutionFeedbackIsCompleteCommandTruthAndNotPhysicalAck() {\n  auto fan = makePolicy();\n  auto humidifier = makePolicy();\n  auto store = makeStore();\n  const auto supervisor_config = makeSupervisorConfig(fan, humidifier);\n  output::OutputSupervisorResolver resolver(supervisor_config);\n  FakeTransport transport;\n  output::OutputSupervisorExecutor executor(transport, store, supervisor_config);\n  climate_io::ClimateOutputSupervisorSink sink(makeClimateConfig(), resolver, executor, store);\n  sink.setCycleContext(scheduleContext(true));\n\n  climate::ClimateExecutionProjection execution{};\n  assert(sink.applyAndReportExecution(request(1.0F, 1.0F), 5'000U, execution));\n  assert(execution.known_mask == climate::ClimateExecutionKnownAll);\n  assert(execution.known(climate::ClimateExecutionKnownHeater));\n  assert(execution.known(climate::ClimateExecutionKnownCooler));\n  assert(execution.known(climate::ClimateExecutionKnownExhaustFan));\n  assert(execution.known(climate::ClimateExecutionKnownHumidifier));\n  assert(execution.known(climate::ClimateExecutionKnownDehumidifier));\n  assert(execution.known(climate::ClimateExecutionKnownCo2Doser));\n  assert(near(execution.executed.heater, 0.0F));\n  assert(near(execution.executed.cooler, 0.0F));\n  assert(near(execution.executed.exhaust_fan, 1.0F));\n  assert(near(execution.executed.humidifier, 1.0F));\n  assert(near(execution.executed.dehumidifier, 0.0F));\n  assert(near(execution.executed.co2_doser, 0.0F));\n  assertPhysicalUnknown(store, kFan);\n  assertPhysicalUnknown(store, kHumidifier);\n}\n\n'''
p = Path('test/test_climate_output_supervisor_sink/test_main.cpp')
text = p.read_text()
assert text.count(insert_before) == 1
text = text.replace(insert_before, new_test + insert_before, 1)
old_main = '''  testCompleteClimateRequestUsesOneSupervisorCycleAndProjectsCommandTruth();\n  testPartialFailureReturnsFalseAndProjectsLastSuccessfulCommands();\n'''
new_main = '''  testCompleteClimateRequestUsesOneSupervisorCycleAndProjectsCommandTruth();\n  testExecutionFeedbackIsCompleteCommandTruthAndNotPhysicalAck();\n  testPartialFailureReturnsFalseAndProjectsLastSuccessfulCommands();\n'''
assert text.count(old_main) == 1
p.write_text(text.replace(old_main, new_main, 1))

print('A7_3B_EDIT_PASS')
