// Generated by python -m tools.ml.pipeline. Do not edit.
#pragma once

#include <array>
#include <cstddef>

namespace model_golden_vectors {

inline constexpr std::size_t kVectorCount = 3U;
inline constexpr std::size_t kInputCount = 40U;
inline constexpr std::size_t kOutputCount = 4U;
inline constexpr char kSchemaHash[] = "843401551234";
inline constexpr char kModelVersion[] = "environment-mlp-v1-quick-d9e7790d6b99";

inline constexpr std::array<std::array<float, kInputCount>, kVectorCount> kFeatures{{
        {{0.481550694f, 0.578374028f, 0.093241878f, 0.38913703f, 0.722963214f, 0.263415158f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.023682596f, 0.003780596f, 0.002394693f, 0.068505161f, 0.126990497f, 0.035310917f, 0.040543132f, 1.0f, 0.047108084f, 0.679890513f, 0.0f, 0.0f, 0.0f, 0.256479055f, 1.0f, 0.037275974f, 0.0f, 0.0f, 0.0f, 0.019452276f, 0.619330764f, 0.702956259f, 0.251970828f, 0.622257888f, 0.0f, 0.0f, 0.0f, 0.0f}},
        {{0.468009323f, 0.32335633f, 0.162833467f, 0.259074122f, 0.456310511f, 0.683771074f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.02888309f, 0.015673162f, 0.004601685f, 0.012334581f, 0.277590245f, 0.056245811f, 0.100644343f, 1.0f, 0.03230701f, 0.700775445f, 0.0f, 1.0f, 0.043765139f, 0.25028199f, 1.0f, 0.013227667f, 1.0f, 0.01941861f, 0.018338971f, 0.008732271f, 0.582657874f, 0.639372826f, 0.113880813f, 0.571964979f, 0.0f, 0.0f, 0.0f, 0.0f}},
        {{0.482297808f, 0.582556784f, 0.094062366f, 0.391781569f, 0.722908676f, 0.262772709f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.023682596f, 0.003780596f, 0.002394693f, 0.068505161f, 0.126990497f, 0.035310917f, 0.040543132f, 1.0f, 0.047108084f, 0.679890513f, 0.0f, 0.0f, 0.0f, 0.256479055f, 1.0f, 0.037275974f, 0.0f, 0.0f, 0.0f, 0.019452276f, 0.619330764f, 0.702956259f, 0.251970828f, 0.622257888f, 1.0f, 0.0f, 0.0f, 0.0f}}
}};
inline constexpr std::array<std::array<float, kOutputCount>, kVectorCount> kExpected{{
        {{0.2151916f, 0.1411853f, 0.389479f, 0.1231977f}},
        {{0.2020508f, 0.139834f, 0.3890193f, 0.1062265f}},
        {{0.2293568f, 0.1350279f, 0.3599121f, 0.1044787f}}
}};

}  // namespace model_golden_vectors
