// Generated by python -m tools.ml.pipeline. Do not edit.
#pragma once

#include <array>
#include <cstddef>

namespace model_golden_vectors {

inline constexpr std::size_t kVectorCount = 3U;
inline constexpr std::size_t kInputCount = 43U;
inline constexpr std::size_t kOutputCount = 4U;
inline constexpr char kSchemaHash[] = "e12b0cc20edf";
inline constexpr char kModelVersion[] = "environment-mlp-v1-quick-fabd3736e51d";

inline constexpr std::array<std::array<float, kInputCount>, kVectorCount> kFeatures{{
        {{0.481529921f, 0.577023923f, 0.092755921f, 0.390000284f, 0.722524524f, 0.263407111f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.023682596f, 0.003780596f, 0.002394693f, 0.068505161f, 0.126990497f, 0.035310917f, 0.040543132f, 1.0f, 0.047108084f, 0.679890513f, 0.0f, 0.0f, 0.0f, 0.256479055f, 0.0f, 1.0f, 0.037275974f, 1.0f, 0.0f, 0.0f, 0.0f, 0.015442013f, 1.0f, 0.591595173f, 0.575512946f, 0.240305454f, 0.464323997f, 0.0f, 0.0f, 0.0f, 0.0f}},
        {{0.468236148f, 0.323484838f, 0.163109422f, 0.258321553f, 0.456268311f, 0.683622539f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.02888309f, 0.015673162f, 0.004601685f, 0.012334581f, 0.277590245f, 0.056245811f, 0.100644343f, 1.0f, 0.03230701f, 0.700775445f, 0.0f, 1.0f, 0.043765139f, 0.25028199f, 1.0f, 1.0f, 0.013227667f, 0.0f, 1.0f, 0.01941861f, 0.018338971f, 0.011909602f, 0.0f, 0.569984972f, 0.648567677f, 0.175717816f, 0.393342376f, 0.0f, 0.0f, 0.0f, 0.0f}},
        {{0.481751829f, 0.577175856f, 0.09362004f, 0.390432268f, 0.722377002f, 0.262888342f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.023682596f, 0.003780596f, 0.002394693f, 0.068505161f, 0.126990497f, 0.035310917f, 0.040543132f, 1.0f, 0.047108084f, 0.679890513f, 0.0f, 0.0f, 0.0f, 0.256479055f, 0.0f, 1.0f, 0.037275974f, 1.0f, 0.0f, 0.0f, 0.0f, 0.015442013f, 1.0f, 0.591595173f, 0.575512946f, 0.240305454f, 0.464323997f, 0.0f, 0.0f, 0.0f, 0.0f}}
}};
inline constexpr std::array<std::array<float, kOutputCount>, kVectorCount> kExpected{{
        {{0.1116794f, 0.1425118f, 0.5437734f, 0.1468591f}},
        {{0.142048f, 0.1316703f, 0.4600743f, 0.1013931f}},
        {{0.1116782f, 0.1424994f, 0.5437589f, 0.1468911f}}
}};

}  // namespace model_golden_vectors
